// Provider Presets (one-click setup templates).

package store

// Preset — template for one-click provider setup.
type Preset struct {
	ID            string   `json:"id"`             // "openai", "anthropic-api", "anthropic-sub", "deepseek", ...
	Name          string   `json:"name"`           // display name
	Icon          string   `json:"icon"`           // emoji
	Description   string   `json:"description"`    // tagline
	Provider      string   `json:"provider"`       // internal provider type
	AuthType      string   `json:"authType"`       // api_key | subscription | none
	Format        string   `json:"format"`         // openai | anthropic | gemini
	BaseURL       string   `json:"baseUrl"`        // upstream endpoint
	Priority      int      `json:"priority"`       // default priority
	Models        []string `json:"models"`         // pre-filled list
	NeedsAPIKey   bool     `json:"needsApiKey"`    // show API key field
	NeedsURL      bool     `json:"needsUrl"`       // show base URL field (custom only)
	TokenSource   string   `json:"tokenSource,omitempty"` // subscription source
	APIKeyHint    string   `json:"apiKeyHint,omitempty"`  // placeholder hint
	APIKeyURL     string   `json:"apiKeyUrl,omitempty"`   // where to get key
	Free          bool     `json:"free"`           // free tier hint
	Tag           string   `json:"tag,omitempty"`  // "cheap", "fast", "free", "premium"
	QuotaResetHours float64 `json:"quotaResetHours,omitempty"` // rolling quota window (hours); 0 = none
}

// Presets — curated list of supported providers. Easy to extend.
var Presets = []Preset{
	{
		ID:          "anthropic-sub",
		Name:        "Claude (Pro/Max Subscription)",
		Icon:        "🟣",
		Description: "Use your existing Claude subscription — no API key needed.",
		Provider:    "anthropic",
		AuthType:    AuthTypeSubscription,
		Format:      "anthropic",
		BaseURL:     "https://api.anthropic.com/v1",
		Priority:    10,
		Models: []string{
			"claude-opus-4-7", "claude-opus-4-6",
			"claude-sonnet-4-6", "claude-sonnet-4-5",
			"claude-haiku-4-5",
		},
		NeedsAPIKey:     false,
		TokenSource:     "claude_credentials",
		Tag:             "premium",
		QuotaResetHours: 5, // Claude Pro/Max rolling 5-hour window (data, editable)
	},
	{
		ID:          "local-llama",
		Name:        "Local llama-server",
		Icon:        "🦙",
		Description: "Local Qwen/Llama via llama.cpp on port 8080 — private and free.",
		Provider:    "local-llama",
		AuthType:    AuthTypeNone,
		Format:      "openai",
		BaseURL:     "http://127.0.0.1:8080/v1",
		Priority:    1,
		Models: []string{
			"qwen3-8b", "qwen*", "llama*", "local-*", "*",
		},
		NeedsAPIKey: false,
		Free:        true,
		Tag:         "free",
	},
	{
		ID:          "openai",
		Name:        "OpenAI",
		Icon:        "🌐",
		Description: "GPT-4/5 family — add your API key (sk-...).",
		Provider:    "openai",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.openai.com/v1",
		Priority:    20,
		Models: []string{
			"gpt-5", "gpt-5-mini", "gpt-4o", "gpt-4o-mini", "o1", "o1-mini",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "sk-...",
		APIKeyURL:   "https://platform.openai.com/api-keys",
		Tag:         "premium",
	},
	{
		ID:          "anthropic-api",
		Name:        "Claude (API Key)",
		Icon:        "🟣",
		Description: "Standard Anthropic API key (sk-ant-...) — if you do not have a subscription.",
		Provider:    "anthropic",
		AuthType:    AuthTypeAPIKey,
		Format:      "anthropic",
		BaseURL:     "https://api.anthropic.com/v1",
		Priority:    15,
		Models: []string{
			"claude-opus-4-7", "claude-sonnet-4-6", "claude-haiku-4-5",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "sk-ant-...",
		APIKeyURL:   "https://console.anthropic.com/settings/keys",
		Tag:         "premium",
	},
	{
		ID:          "deepseek",
		Name:        "DeepSeek",
		Icon:        "🟦",
		Description: "Very cheap — strong reasoning + coding, ~$0.14/1M tokens.",
		Provider:    "deepseek",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.deepseek.com/v1",
		Priority:    30,
		Models: []string{
			"deepseek-chat", "deepseek-reasoner", "deepseek-v3", "deepseek-r1",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "sk-...",
		APIKeyURL:   "https://platform.deepseek.com/api_keys",
		Tag:         "cheap",
	},
	{
		ID:          "gemini",
		Name:        "Google Gemini",
		Icon:        "🟡",
		Description: "Gemini 2.x family — Google AI Studio API key",
		Provider:    "gemini",
		AuthType:    AuthTypeAPIKey,
		Format:      "gemini", // Phase 2: translator needed
		BaseURL:     "https://generativelanguage.googleapis.com/v1beta",
		Priority:    25,
		Models: []string{
			"gemini-3-pro", "gemini-3-flash", "gemini-2.5-flash", "gemini-2.5-pro",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "AIza...",
		APIKeyURL:   "https://aistudio.google.com/apikey",
		Tag:         "premium",
	},
	{
		ID:          "groq",
		Name:        "Groq",
		Icon:        "⚡",
		Description: "Super fast inference (LPU) — Llama + Mixtral free tier generous",
		Provider:    "groq",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.groq.com/openai/v1",
		Priority:    35,
		Models: []string{
			"llama-3.3-70b-versatile", "llama-3.1-8b-instant",
			"mixtral-8x7b-32768", "gemma2-9b-it",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "gsk_...",
		APIKeyURL:   "https://console.groq.com/keys",
		Tag:         "fast",
	},
	{
		ID:          "together",
		Name:        "Together AI",
		Icon:        "🤝",
		Description: "Llama/Qwen/Mistral hosted — pay-per-token, many open-source models.",
		Provider:    "together",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.together.xyz/v1",
		Priority:    40,
		Models: []string{
			"meta-llama/Llama-3.3-70B-Instruct-Turbo",
			"Qwen/Qwen2.5-72B-Instruct-Turbo",
			"deepseek-ai/DeepSeek-R1",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "tgp_...",
		APIKeyURL:   "https://api.together.xyz/settings/api-keys",
		Tag:         "premium",
	},
	{
		ID:          "openrouter",
		Name:        "OpenRouter",
		Icon:        "🔗",
		Description: "Aggregator of 100+ models behind one API — Claude/GPT/Llama/etc. via a single key.",
		Provider:    "openrouter",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://openrouter.ai/api/v1",
		Priority:    50,
		Models: []string{
			"openai/gpt-4o", "anthropic/claude-3.5-sonnet",
			"google/gemini-pro-1.5", "meta-llama/llama-3.3-70b-instruct",
			"deepseek/deepseek-chat",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "sk-or-...",
		APIKeyURL:   "https://openrouter.ai/keys",
		Tag:         "premium",
	},
	// ── FREE TIER (Kiro free Claude — flagship preset) ───────────────
	{
		ID:          "kiro-ai",
		Name:        "Kiro AI (Free Claude Unlimited)",
		Icon:        "🆓",
		Description: "Free Claude Sonnet/Opus via Kiro signup — flagship free preset.",
		Provider:    "kiro",
		AuthType:    AuthTypeSubscription,
		Format:      "anthropic",
		BaseURL:     "https://api.kiro.dev/v1",
		Priority:    5,
		Models: []string{
			"kr/claude-sonnet-4.5", "kr/claude-opus-4", "kr/claude-haiku",
		},
		NeedsAPIKey: false,
		TokenSource: "kiro_oauth",
		Free:        true,
		Tag:         "free",
	},
	{
		ID:          "opencode",
		Name:        "OpenCode (Free, No Auth)",
		Icon:        "🟢",
		Description: "Free tier, no signup — limited models but enough for development.",
		Provider:    "opencode",
		AuthType:    AuthTypeNone,
		Format:      "openai",
		BaseURL:     "https://api.opencode.ai/v1",
		Priority:    8,
		Models: []string{
			"opencode/gpt-3.5-turbo", "opencode/llama-3-8b",
		},
		NeedsAPIKey: false,
		Free:        true,
		Tag:         "free",
	},

	// ── PREMIUM CLOUD (big-name) ───────────────────────────────────
	{
		ID:          "vertex-ai",
		Name:        "Google Vertex AI",
		Icon:        "☁️",
		Description: "Gemini + Claude (Vertex partner) + DeepSeek + Qwen via Google Cloud",
		Provider:    "vertex",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://us-central1-aiplatform.googleapis.com/v1",
		Priority:    22,
		Models: []string{
			"vertex/gemini-3-pro", "vertex/gemini-2.5-flash",
			"vertex-partner/anthropic/claude-opus-4",
			"vertex-partner/deepseek-ai/deepseek-v3.2-maas",
			"vertex-partner/qwen/qwen3-next-80b-a3b-thinking-maas",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "GCP service account key (JSON paste or env var)",
		APIKeyURL:   "https://console.cloud.google.com/iam-admin/serviceaccounts",
		Tag:         "premium",
	},
	{
		ID:          "mistral",
		Name:        "Mistral AI",
		Icon:        "🌪️",
		Description: "Mistral Large / Codestral / Pixtral — France-based, EU privacy strong",
		Provider:    "mistral",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.mistral.ai/v1",
		Priority:    28,
		Models: []string{
			"mistral-large-latest", "mistral-medium-latest", "codestral-latest",
			"pixtral-large-latest", "ministral-8b-latest",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "...",
		APIKeyURL:   "https://console.mistral.ai/api-keys/",
		Tag:         "premium",
	},
	{
		ID:          "cohere",
		Name:        "Cohere",
		Icon:        "🪶",
		Description: "Command R+ / Aya — strong RAG + multilingual support",
		Provider:    "cohere",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.cohere.ai/v2",
		Priority:    32,
		Models: []string{
			"command-r-plus", "command-r", "command-light", "aya-expanse-32b",
		},
		NeedsAPIKey: true,
		APIKeyURL:   "https://dashboard.cohere.com/api-keys",
		Tag:         "premium",
	},

	// ── FAST INFERENCE (LPU/specialized hardware) ──────────────────
	{
		ID:          "cerebras",
		Name:        "Cerebras",
		Icon:        "⚡",
		Description: "Wafer-scale chip, very fast — Llama 3.1 70B at 600+ tok/s.",
		Provider:    "cerebras",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.cerebras.ai/v1",
		Priority:    36,
		Models: []string{
			"llama3.1-70b", "llama3.1-8b", "llama-3.3-70b",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "csk-...",
		APIKeyURL:   "https://cloud.cerebras.ai/platform/",
		Tag:         "fast",
	},
	{
		ID:          "sambanova",
		Name:        "SambaNova",
		Icon:        "💨",
		Description: "RDU chip — Llama 405B at high speed, good free tier.",
		Provider:    "sambanova",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.sambanova.ai/v1",
		Priority:    37,
		Models: []string{
			"Meta-Llama-3.3-70B-Instruct", "Meta-Llama-3.1-405B-Instruct",
			"Qwen2.5-72B-Instruct",
		},
		NeedsAPIKey: true,
		APIKeyURL:   "https://cloud.sambanova.ai/apis",
		Tag:         "fast",
	},
	{
		ID:          "hyperbolic",
		Name:        "Hyperbolic",
		Icon:        "🌀",
		Description: "Open-source models cheap — Llama/Qwen/DeepSeek/Hermes 70B+",
		Provider:    "hyperbolic",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.hyperbolic.xyz/v1",
		Priority:    42,
		Models: []string{
			"meta-llama/Meta-Llama-3.1-405B-Instruct",
			"deepseek-ai/DeepSeek-R1",
			"NousResearch/Hermes-3-Llama-3.1-70B",
			"Qwen/Qwen2.5-72B-Instruct",
		},
		NeedsAPIKey: true,
		APIKeyURL:   "https://app.hyperbolic.xyz/settings",
		Tag:         "cheap",
	},

	// ── CHEAP + OPEN SOURCE HOSTS ──────────────────────────────────
	{
		ID:          "fireworks",
		Name:        "Fireworks AI",
		Icon:        "🎆",
		Description: "Fast OSS inference — Llama/DeepSeek/Mixtral hosted serverless",
		Provider:    "fireworks",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.fireworks.ai/inference/v1",
		Priority:    44,
		Models: []string{
			"accounts/fireworks/models/llama-v3p3-70b-instruct",
			"accounts/fireworks/models/deepseek-r1",
			"accounts/fireworks/models/qwen2p5-72b-instruct",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "fw_...",
		APIKeyURL:   "https://fireworks.ai/account/api-keys",
		Tag:         "cheap",
	},
	{
		ID:          "deepinfra",
		Name:        "DeepInfra",
		Icon:        "🟦",
		Description: "OSS hosted models, very cheap — Llama 405B at $0.5/1M.",
		Provider:    "deepinfra",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.deepinfra.com/v1/openai",
		Priority:    46,
		Models: []string{
			"meta-llama/Meta-Llama-3.1-405B-Instruct",
			"deepseek-ai/DeepSeek-V3",
			"Qwen/Qwen2.5-72B-Instruct",
		},
		NeedsAPIKey: true,
		APIKeyURL:   "https://deepinfra.com/dash/api_keys",
		Tag:         "cheap",
	},
	{
		ID:          "novita",
		Name:        "Novita AI",
		Icon:        "🟣",
		Description: "DeepSeek + Llama + Qwen hosted — competitive pricing",
		Provider:    "novita",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.novita.ai/v3/openai",
		Priority:    48,
		Models: []string{
			"deepseek/deepseek-r1", "deepseek/deepseek-v3",
			"meta-llama/llama-3.3-70b-instruct",
			"qwen/qwen-2.5-72b-instruct",
		},
		NeedsAPIKey: true,
		APIKeyURL:   "https://novita.ai/settings/key-management",
		Tag:         "cheap",
	},

	// ── ASIA-PACIFIC ───────────────────────────────────────────────
	{
		ID:          "moonshot",
		Name:        "Moonshot (Kimi K2)",
		Icon:        "🌙",
		Description: "Kimi K2 + K1.5 — strong long-context (128K-2M) reasoning.",
		Provider:    "moonshot",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.moonshot.cn/v1",
		Priority:    52,
		Models: []string{
			"kimi-k2-0905-preview", "kimi-latest", "moonshot-v1-128k",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "sk-...",
		APIKeyURL:   "https://platform.moonshot.cn/console/api-keys",
		Tag:         "premium",
	},
	{
		ID:          "zhipuai",
		Name:        "Zhipu GLM",
		Icon:        "🟢",
		Description: "GLM-4 / GLM-Plus China — multilingual + tool use",
		Provider:    "zhipuai",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://open.bigmodel.cn/api/paas/v4",
		Priority:    54,
		Models: []string{
			"glm-4.6", "glm-4-plus", "glm-4-flash", "glm-4v",
		},
		NeedsAPIKey: true,
		APIKeyURL:   "https://open.bigmodel.cn/usercenter/apikeys",
		Tag:         "premium",
	},
	{
		ID:          "qwen-cloud",
		Name:        "Qwen DashScope (Alibaba Cloud)",
		Icon:        "🟠",
		Description: "Qwen3 plus/max/coder via Alibaba Cloud DashScope API.",
		Provider:    "qwen-cloud",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://dashscope.aliyuncs.com/compatible-mode/v1",
		Priority:    56,
		Models: []string{
			"qwen3-max", "qwen3-coder-plus", "qwen3-235b-a22b-instruct",
			"qwen3-vl-plus",
		},
		NeedsAPIKey: true,
		APIKeyURL:   "https://dashscope.console.aliyun.com/apiKey",
		Tag:         "premium",
	},

	// ── REALTIME / SEARCH-AWARE ────────────────────────────────────
	{
		ID:          "perplexity",
		Name:        "Perplexity",
		Icon:        "🔍",
		Description: "Sonar + Pplx with live web search — best for real-time facts.",
		Provider:    "perplexity",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.perplexity.ai",
		Priority:    58,
		Models: []string{
			"sonar", "sonar-pro", "sonar-reasoning", "sonar-reasoning-pro",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "pplx-...",
		APIKeyURL:   "https://www.perplexity.ai/settings/api",
		Tag:         "premium",
	},
	{
		ID:          "xai-grok",
		Name:        "xAI Grok",
		Icon:        "❌",
		Description: "Grok 4 / Grok 4.1 — Elon Musk's xAI, web-aware + realtime",
		Provider:    "xai",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.x.ai/v1",
		Priority:    60,
		Models: []string{
			"grok-4", "grok-4-heavy", "grok-4.1-thinking", "grok-3", "grok-vision-beta",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "xai-...",
		APIKeyURL:   "https://console.x.ai/team/default/api-keys",
		Tag:         "premium",
	},

	// ── LOCAL ALTERNATIVES ─────────────────────────────────────────
	{
		ID:          "ollama",
		Name:        "Ollama (Local)",
		Icon:        "🦙",
		Description: "Ollama local instance — different from llama-server, default port 11434.",
		Provider:    "ollama",
		AuthType:    AuthTypeNone,
		Format:      "openai",
		BaseURL:     "http://127.0.0.1:11434/v1",
		Priority:    3,
		Models: []string{
			"llama3.3", "qwen3", "deepseek-r1", "mistral", "gemma3", "*",
		},
		NeedsAPIKey: false,
		Free:        true,
		Tag:         "free",
	},
	{
		ID:          "lmstudio",
		Name:        "LM Studio (Local)",
		Icon:        "🎨",
		Description: "LM Studio desktop app — default port 1234, GUI model loader",
		Provider:    "lmstudio",
		AuthType:    AuthTypeNone,
		Format:      "openai",
		BaseURL:     "http://127.0.0.1:1234/v1",
		Priority:    4,
		Models:      []string{"*"},
		NeedsAPIKey: false,
		Free:        true,
		Tag:         "free",
	},
	{
		ID:          "vllm-local",
		Name:        "vLLM (Local)",
		Icon:        "🚀",
		Description: "vLLM self-hosted inference — high throughput, default port 8000",
		Provider:    "vllm",
		AuthType:    AuthTypeNone,
		Format:      "openai",
		BaseURL:     "http://127.0.0.1:8000/v1",
		Priority:    6,
		Models:      []string{"*"},
		NeedsAPIKey: false,
		Free:        true,
		Tag:         "free",
	},

	// ── GATEWAY / PROXY ────────────────────────────────────────────
	{
		ID:          "litellm",
		Name:        "LiteLLM Proxy",
		Icon:        "🪶",
		Description: "Self-hosted LiteLLM gateway — proxies 100+ providers behind one endpoint.",
		Provider:    "litellm",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "http://127.0.0.1:4000/v1",
		Priority:    62,
		Models:      []string{"*"},
		NeedsAPIKey: true,
		NeedsURL:    true,
		APIKeyHint:  "sk-... (LiteLLM master key)",
	},
	{
		ID:          "cloudflare-ai",
		Name:        "Cloudflare Workers AI",
		Icon:        "☁️",
		Description: "Workers AI — Llama/Mistral hosted on Cloudflare's global edge.",
		Provider:    "cloudflare",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.cloudflare.com/client/v4/accounts/{ACCOUNT_ID}/ai/v1",
		Priority:    64,
		Models: []string{
			"@cf/meta/llama-3.3-70b-instruct",
			"@cf/mistral/mistral-7b-instruct-v0.2",
		},
		NeedsAPIKey: true,
		NeedsURL:    true, // account ID in URL — user edit
		APIKeyURL:   "https://dash.cloudflare.com/profile/api-tokens",
		Tag:         "cheap",
	},

	// ── IDE SUBSCRIPTIONS (paste your subscription token) ──────────────
	// These wrap IDE-bundled AI subscriptions. Token is whatever your IDE
	// stores after login — paste it in the API key field. Endpoints and
	// model lists are best-effort; some providers may need manual override.
	{
		ID:          "codeium-plus",
		Name:        "Codeium Plus",
		Icon:        "🧊",
		Description: "Codeium Plus ($15/mo) — paste your Codeium API key; OpenAI-compat passthrough.",
		Provider:    "codeium",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.codeium.com/v1",
		Priority:    14,
		Models: []string{
			"gpt-4o", "gpt-4o-mini", "claude-3-5-sonnet",
			"deepseek-v3", "gemini-2.0-flash",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "from ~/.codeium/config.json or codeium.com/profile",
		APIKeyURL:   "https://codeium.com/profile",
		Tag:         "premium",
	},
	{
		ID:          "windsurf-cascade",
		Name:        "Windsurf Cascade",
		Icon:        "🏄",
		Description: "Windsurf Cascade ($15/mo, by Codeium) — paste Windsurf API key. EXPERIMENTAL: protocol native is gRPC; openai-compat passthrough may need endpoint override.",
		Provider:    "windsurf",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://server.codeium.com/v1",
		Priority:    15,
		Models: []string{
			"windsurf/gpt-4o", "windsurf/claude-3-5-sonnet",
			"windsurf/deepseek-v3", "windsurf/swe-1",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "Windsurf account token",
		APIKeyURL:   "https://codeium.com/windsurf/account",
		Tag:         "premium",
	},
	{
		ID:          "jetbrains-ai",
		Name:        "JetBrains AI Pro",
		Icon:        "🧠",
		Description: "JetBrains AI Pro/Ultimate — Grazie proxy, multi-model. Custom auth header (Grazie-Authenticate-JWT).",
		Provider:    "jetbrains_ai",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "https://api.grazie.ai/api/v5",
		Priority:    16,
		Models: []string{
			"jetbrains/gpt-4o", "jetbrains/claude-3-5-sonnet",
			"jetbrains/o1-mini", "jetbrains/gemini-1.5-pro",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "Grazie JWT — IDE → Settings → Tools → AI Assistant → Get token",
		APIKeyURL:   "https://www.jetbrains.com/ai/",
		Tag:         "premium",
	},
	{
		ID:          "zed-ai",
		Name:        "Zed AI",
		Icon:        "⚡",
		Description: "Zed editor subscription — Claude family via Zed's hosted proxy. EXPERIMENTAL: endpoint may require override.",
		Provider:    "zed_ai",
		AuthType:    AuthTypeAPIKey,
		Format:      "anthropic",
		BaseURL:     "https://zed.dev/api",
		Priority:    17,
		Models: []string{
			"zed/claude-3-5-sonnet", "zed/claude-3-opus", "zed/claude-3-5-haiku",
		},
		NeedsAPIKey: true,
		APIKeyHint:  "Zed account API key from zed.dev/account",
		APIKeyURL:   "https://zed.dev/account",
		Tag:         "premium",
	},

	// ── CUSTOM (catch-all) ─────────────────────────────────────────
	{
		ID:          "custom",
		Name:        "Custom (OpenAI-compat)",
		Icon:        "⚙️",
		Description: "Any other self-hosted OpenAI-compatible service not listed here.",
		Provider:    "custom",
		AuthType:    AuthTypeAPIKey,
		Format:      "openai",
		BaseURL:     "",
		Priority:    100,
		Models:      []string{"*"},
		NeedsAPIKey: true,
		NeedsURL:    true,
		APIKeyHint:  "(optional if no auth)",
	},
}

// GetPreset returns preset by ID. Returns nil if not found.
func GetPreset(id string) *Preset {
	for i := range Presets {
		if Presets[i].ID == id {
			return &Presets[i]
		}
	}
	return nil
}
